config/routes.rb
Rails.application.routes.draw do
  resources :party_company_details
  resources :party_person_details
  resources :persons
  resources :companies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "party_company_details#index"
end

app/models/accountability.rb
class Accountability < EntityRelationship
  belongs_to :parent, foreign_key: :parent_id, class_name: "Party"
  belongs_to :child, foreign_key: :child_id, class_name: "Party"
end

app/models/accountability_type.rb
class AccountabilityType < EntityType
  has_many :accountabilities, -> { where(type: "Accountability") }, class_name: "EntityRelationship", foreign_key: :relationship_id
end

app/models/allowed_relationship.rb
class AllowedRelationship < ApplicationRecord
  belongs_to :party_type
  belongs_to :relationship_type
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/entity_relationship.rb
class EntityRelationship < ApplicationRecord
  belongs_to :relationship, polymorphic: true
end

app/models/entity_type.rb
class EntityType < ApplicationRecord
end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :party_type
  belongs_to :detail, polymorphic: true
  has_many :from_relationships, foreign_key: :parent_id, class_name: "Relationship"
  has_many :to_relationships, foreign_key: :child_id, class_name: "Relationship"
end

app/models/party_company_detail.rb
class PartyCompanyDetail < ApplicationRecord
  has_one :party, -> { where(detail_type: "PartyCompanyDetail") }, foreign_key: :detail_id
  belongs_to :category
  
  delegate :name, to: :category, prefix: :category
  def type = party&.party_type&.name
  #def employees = party&.from_relationships.map{|x| x&.to&.detail&.full_name }.uniq
  #def employees = party&.from_relationships.map{|x| [x&.to&.detail&.full_name, x&.to.detail.party.to_relationships.map{|x| [x&.relationship&.name, x&.from&.detail&.official_name]} ]  }.uniq
  def employees = party&.from_relationships.map do |rel| 
    [rel.to.detail_id, rel&.to&.detail&.full_name, rel&.to.detail.party.to_relationships.map do |rel| 
      rel&.relationship&.name
    end 
    ]  
  end.uniq

  def areas = party&.to_relationships.map do |area|
    area&.from&.detail&.name
  end
end

app/models/party_generic_detail.rb
class PartyGenericDetail < ApplicationRecord
  has_one :party, -> { where(detail_type: "PartyGenericDetail") }, foreign_key: :detail_id
end

app/models/party_person_detail.rb
class PartyPersonDetail < ApplicationRecord
  has_one :party, -> { where(detail_type: "PartyPersonDetail") }, foreign_key: :detail_id

  def full_name = "#{first_name} #{last_name}"
  def type = party&.party_type&.name
  def person_types = party&.to_relationships.map{|x| [x&.relationship&.name, x&.from&.detail&.official_name]}
end

app/models/party_type.rb
class PartyType < EntityType
  has_many :parties
  has_one :allowed_relationship
end

app/models/relationship.rb
class Relationship < EntityRelationship
  belongs_to :from, foreign_key: :parent_id, class_name: "Party"
  belongs_to :to, foreign_key: :child_id, class_name: "Party"
end

app/models/relationship_type.rb
class RelationshipType < EntityType
  has_many :relationships, -> { where(type: "Relationship") }, class_name: "EntityRelationship", foreign_key: :relationship_id
  has_one :allowed_relationship
end

app/models/user_company.rb
class UserCompany
  attr_accessor :id, :name, :type, :email, :management, :updated_at

  def initialize(id:, name:, type:, email:, management:, updated_at:)
    @id = id
    @name = name
    @type = type
    @email = email
    @management = management
    @updated_at = updated_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  I18n.default_locale = :es
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = PartyCompanyDetail.all
  end

  def show
    @company = PartyCompanyDetail.find_by_id(params[:id])
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def index
    @persons = PartyPersonDetail.all
  end

  def show
    @person = PartyPersonDetail.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/party_company_details_helper.rb
module PartyCompanyDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DirectoryDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column" style="min-height: 100vh">
    <%= render "shared/nav" %>
    </br>
    <div class="container flex-fill">
      <div class="flex-xl-nowrap">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href=<%= root_path %>>Main</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href=<%= new_party_person_detail_path %>>Crear Persona</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= new_party_company_detail_path %>>Crear Empresa</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= persons_path %>>Personas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= companies_path %>>Empresas</a>
        </li>
      </ul>
      <!--
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      -->
    </div>
  </div>
</nav>