config/routes.rb
Rails.application.routes.draw do
  resources :party_company_details
  resources :party_person_details
  resources :persons
  resources :companies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "party_company_details#index"
end

app/models/accountability.rb
class Accountability < EntityRelationship
  belongs_to :parent, foreign_key: :parent_id, class_name: "Party"
  belongs_to :child, foreign_key: :child_id, class_name: "Party"
end

app/models/accountability_type.rb
class AccountabilityType < EntityType
  has_many :accountabilities, -> { where(type: "Accountability") }, class_name: "EntityRelationship", foreign_key: :relationship_id
end

app/models/allowed_relationship.rb
class AllowedRelationship < ApplicationRecord
  belongs_to :party_type
  belongs_to :relationship_type
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/entity_relationship.rb
class EntityRelationship < ApplicationRecord
  belongs_to :relationship, polymorphic: true
end

app/models/entity_type.rb
class EntityType < ApplicationRecord
end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :party_type
  belongs_to :detail, polymorphic: true
  has_many :from_relationships, foreign_key: :parent_id, class_name: "Relationship"
  has_many :to_relationships, foreign_key: :child_id, class_name: "Relationship"
end

app/models/party_company_detail.rb
class PartyCompanyDetail < ApplicationRecord
  has_one :party, -> { where(detail_type: "PartyCompanyDetail") }, foreign_key: :detail_id
  belongs_to :category
  
  delegate :name, to: :category, prefix: :category
  def type = party&.party_type&.name
  #def employees = party&.from_relationships.map{|x| x&.to&.detail&.full_name }.uniq
  #def employees = party&.from_relationships.map{|x| [x&.to&.detail&.full_name, x&.to.detail.party.to_relationships.map{|x| [x&.relationship&.name, x&.from&.detail&.official_name]} ]  }.uniq
  def employees = party&.from_relationships.map do |rel| 
    [rel.to.detail_id, rel&.to&.detail&.full_name, rel&.to.detail.party.to_relationships.map do |rel| 
      rel&.relationship&.name
    end 
    ]  
  end.uniq

  def areas = party&.to_relationships.map do |area|
    area&.from&.detail&.name
  end
end

app/models/party_generic_detail.rb
class PartyGenericDetail < ApplicationRecord
  has_one :party, -> { where(detail_type: "PartyGenericDetail") }, foreign_key: :detail_id
end

app/models/party_person_detail.rb
class PartyPersonDetail < ApplicationRecord
  has_one :party, -> { where(detail_type: "PartyPersonDetail") }, foreign_key: :detail_id

  def full_name = "#{first_name} #{last_name}"
  def type = party&.party_type&.name
  def person_types = party&.to_relationships.map{|x| [x&.relationship&.name, x&.from&.detail&.official_name]}
end

app/models/party_type.rb
class PartyType < EntityType
  has_many :parties
  has_one :allowed_relationship
end

app/models/relationship.rb
class Relationship < EntityRelationship
  belongs_to :from, foreign_key: :parent_id, class_name: "Party"
  belongs_to :to, foreign_key: :child_id, class_name: "Party"
end

app/models/relationship_type.rb
class RelationshipType < EntityType
  has_many :relationships, -> { where(type: "Relationship") }, class_name: "EntityRelationship", foreign_key: :relationship_id
  has_one :allowed_relationship
end

app/models/user_company.rb
class UserCompany
  attr_accessor :id, :name, :type, :email, :management, :updated_at

  def initialize(id:, name:, type:, email:, management:, updated_at:)
    @id = id
    @name = name
    @type = type
    @email = email
    @management = management
    @updated_at = updated_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  I18n.default_locale = :es
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = PartyCompanyDetail.all
  end

  def show
    @company = PartyCompanyDetail.find_by_id(params[:id])
  end
end

app/controllers/party_person_details_controller.rb
class PartyPersonDetailsController < ApplicationController
  def new
    @party_person_detail = PartyPersonDetail.new
  end

  def edit
  end

  def create
    @party_person_detail = PartyPersonDetail.new(party_person_detail_params.except(:company_id))
    respond_to do |format|
      if @party_person_detail.save
        party_person = Party.create(
          party_type: person_company,
          detail: @party_person_detail
        )
        if params.dig(:party_person_detail, :company_id).present?
          Relationship.create(
            relationship: worker_of,
            from: company.party,
            to: party_person
          )
        end

        format.html { redirect_to party_person_detail_url(@party_person_detail), notice: "Party person detail was successfully created." }
        format.json { render :show, status: :created, location: @party_person_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @party_person_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def party_person_detail_params
    params.require(:party_person_detail).permit(:first_name, :last_name, :phone, :email, :person_address, :identification_document_number, :identification_document_type, :company_id)
  end

  def worker_of
    @worker_of ||= RelationshipType.find_by(name: "trabajador")
  end

  def company
    @company ||= PartyCompanyDetail.find_by_id(params.dig(:party_person_detail, :company_id))
  end

  def person_company
    @person_company ||= PartyType.find_by(name: "person")
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def index
    @persons = PartyPersonDetail.all
  end

  def show
    @person = PartyPersonDetail.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/party_company_details_helper.rb
module PartyCompanyDetailsHelper
end

app/views/companies/_company_detail.html.erb
<tr id=<%= dom_id company_detail %>>
  <th scope="row"><%= company_detail.common_name %></th> 
  <th scope="row"><%= t("models.#{company_detail.type}") %></th> 
  <th scope="row"><%= company_detail.email_company %></th> 
  <th scope="row">Administrador General</th> 
  <th scope="row"><%= company_detail.category_name %></th>
  <th scope="row"><%= company_detail.updated_at %></th>
  <th>
    <%= link_to "Ver", company_path(company_detail), { class: 'btn-sm btn-primary btn' } %>
  </th>
</tr>

app/views/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Empresas</h1>

<div id="companies">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Tipo</th>
        <th scope="col">Email</th>
        <th scope="col">Creado por</th>
        <th scope="col">Categoria</th>
        <th scope="col">Ultima actualizacion</th>
        <th scope="col">Ver detalles</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "company_detail", collection: @companies %>
    </tbody>
  </table>
</div>

app/views/companies/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-header">
    Empresa
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Nombre: <%= @company.common_name %></li>
    <li class="list-group-item">Tipo: <%= @company.type %></li>
    <li class="list-group-item">Email: <%= @company.email_company %></li>
  </ul>
</div>

<div class="mt-3 row row-cols-1 row-cols-md-3 g-4">
  <% @company.areas.each do |area| %>
  <div class="col">
    <div class="card mt-4" style="width: 18rem;">
      <div class="card-header">
        Area
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Nombre: <%= area %>
      </ul>
      </div>
    </div>
  <% end %>
</div>

<div class="mt-3 row row-cols-1 row-cols-md-3 g-4">
  <% @company.employees.each do |employee| %>
  <div class="col">
    <div class="card mt-4" style="width: 18rem;">
      <div class="card-header">
        Persona
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Nombre: <%= employee.second %>
        <% employee.last.each do |cargo| %>
          <li class="list-group-item">Es <%= cargo %></li>
        <% end %>
        <li class="list-group-item">
            <%= link_to "Ver", person_path(employee.first), { class: 'btn-sm btn-primary btn' } %>
        </li>
      </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/persons/_person_detail.html.erb
<tr id=<%= dom_id person_detail %>>
  <th scope="row"><%= person_detail.full_name %></th> 
  <th scope="row"><%= t("models.#{person_detail.type}") %></th> 
  <th scope="row"><%= person_detail.email %></th> 
  <th scope="row">Administrador General</th> 
  <th scope="row"><%= person_detail.updated_at %></th>
  <th>
    <%= link_to "Ver", person_path(person_detail), { class: 'btn-sm btn-primary btn' } %>
  </th>
</tr>

app/views/persons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Personas</h1>

<div id="persons">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Tipo</th>
        <th scope="col">Email</th>
        <th scope="col">Creado por</th>
        <th scope="col">Ultima actualizacion</th>
        <th scope="col">Ver detalles</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "person_detail", collection: @persons %>
    </tbody>
  </table>
</div>

app/views/persons/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-header">
    Person
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Nombre: <%= @person.full_name %></li>
    <li class="list-group-item">Tipo: <%= @person.type %></li>
    <li class="list-group-item">Email: <%= @person.email %></li>
  </ul>
</div>

<div class="card mt-4" style="width: 18rem;">
  <div class="card-header">
    Relaciones
  </div>
  <ul class="list-group list-group-flush">
    <% @person.person_types.each do |cargo| %>
      <li class="list-group-item">Es <%= cargo.first %> de la compañia <%= cargo.last %></li>
    <% end %>
  </ul>
</div>