config/routes.rb
Rails.application.routes.draw do
  resources :party_company_details
  resources :party_person_details
  resources :persons
  resources :companies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "party_company_details#index"
end

app/models/party_company_detail.rb
class PartyCompanyDetail < ApplicationRecord
  has_one :party, -> { where(detail_type: "PartyCompanyDetail") }, foreign_key: :detail_id
  belongs_to :category
  
  delegate :name, to: :category, prefix: :category
  def type = party&.party_type&.name
  #def employees = party&.from_relationships.map{|x| x&.to&.detail&.full_name }.uniq
  #def employees = party&.from_relationships.map{|x| [x&.to&.detail&.full_name, x&.to.detail.party.to_relationships.map{|x| [x&.relationship&.name, x&.from&.detail&.official_name]} ]  }.uniq
  def employees = party&.from_relationships.map do |rel| 
    [rel.to.detail_id, rel&.to&.detail&.full_name, rel&.to.detail.party.to_relationships.map do |rel| 
      rel&.relationship&.name
    end 
    ]  
  end.uniq

  def areas = party&.to_relationships.map do |area|
    area&.from&.detail&.name
  end
end

app/controllers/party_company_details_controller.rb
class PartyCompanyDetailsController < ApplicationController
  before_action :set_party_company_detail, only: %i[ show edit update destroy ]

  # GET /party_company_details or /party_company_details.json
  def index
    companies = PartyCompanyDetail.all.each_with_object([]) do |x, arr|
      management = if x.party&.from_relationships&.first&.relationship&.name.present?
                     "Tiene como #{x.party&.from_relationships&.first.relationship&.name} legal a #{x.party.from_relationships&.first.to&.detail&.slice(:first_name, :last_name)&.values&.join(" ")}"
                   else
                     "No tiene representante legal"
                   end
      arr << UserCompany.new(id: x.id,
                             name: x.common_name,
                             type: x.party.party_type.name,
                             email: x.email_company,
                             management: management,
                             updated_at: x.updated_at)
    end
    users = PartyPersonDetail.all.each_with_object([]){|x, arr| arr << UserCompany.new(id: x.id, name: "#{x.first_name} #{x.last_name}", type: x.party.party_type.name, email: x.email, management: "Es #{x.party&.to_relationships&.first.relationship&.name} de #{x.party&.to_relationships&.first.from&.detail&.official_name}", updated_at: x.updated_at) } 
    @companies = (companies + users).sort_by{|x| x.name }
  end

  # GET /party_company_details/1 or /party_company_details/1.json
  def show
  end

  # GET /party_company_details/new
  def new
    @party_company_detail = PartyCompanyDetail.new
  end

  # GET /party_company_details/1/edit
  def edit
  end

  # POST /party_company_details or /party_company_details.json
  def create
    @party_company_detail = PartyCompanyDetail.new(party_company_detail_params)
    respond_to do |format|
      if @party_company_detail.save
        party_company = Party.create(
          party_type: party_type_company,
          detail: @party_company_detail
        )

        if party_responsible_params.values.all?(&:present?)
          person = PartyPersonDetail.create(party_responsible_params)
          party_person = Party.create(
            party_type: person_company,
            detail: person
          )
          Relationship.create(
            relationship: responsible_company,
            from: party_company,
            to: party_person
          )

          Relationship.create(
            relationship: worker_of,
            from: party_company,
            to: party_person
          )
        end
        format.html { redirect_to party_company_detail_url(@party_company_detail), notice: "Party company detail was successfully created." }
        format.json { render :show, status: :created, location: @party_company_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @party_company_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /party_company_details/1 or /party_company_details/1.json
  def update
    respond_to do |format|
      if @party_company_detail.update(party_company_detail_params)
        format.html { redirect_to party_company_detail_url(@party_company_detail), notice: "Party company detail was successfully updated." }
        format.json { render :show, status: :ok, location: @party_company_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @party_company_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /party_company_details/1 or /party_company_details/1.json
  def destroy
    @party_company_detail.destroy

    respond_to do |format|
      format.html { redirect_to party_company_details_url, notice: "Party company detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_party_company_detail
    @party_company_detail = PartyCompanyDetail.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def party_company_detail_params
    params.require(:party_company_detail).permit(:common_name, :official_name, :taxes_registry_number, :country_code, :company_address, :category_id, :email_company)
  end

  def party_responsible_params
    params.require(:party_company_detail).permit(:first_name, :last_name, :phone, :email, :person_address, :identification_document_number, :identification_document_type)
  end

  def party_type_company
    @party_type_company ||= PartyType.find_by(name: "company")
  end

  def responsible_company
    @responsible_company ||= RelationshipType.find_by(name: "representante")
  end

  def person_company
    @person_company ||= PartyType.find_by(name: "person")
  end

  def worker_of
    @worker_of ||= RelationshipType.find_by_name("trabajador")
  end
end

app/helpers/party_company_details_helper.rb
module PartyCompanyDetailsHelper
end

app/views/party_company_details/_form.html.erb
<div class="mb-3 container col-5">
  <%= form_with(model: party_company_detail, class: "form-control" ) do |form| %>
    <% if party_company_detail.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(party_company_detail.errors.count, "error") %> prohibited this party_company_detail from being saved:</h2>

        <ul>
          <% party_company_detail.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :common_name, "Razón Social", style: "display: block", class: "form-label" %>
      <%= form.text_field :common_name, class: "form-control" %>
    </div>

    <div>
      <%= form.label :official_name,"Nombre Oficial", style: "display: block", class: "form-label mt-3"  %>
      <%= form.text_field :official_name, class: "form-control" %>
    </div>

    <div>
      <%= form.label :taxes_registry_number,"Registro único tributario (RUT)", style: "display: block", class: "form-label mt-3" %>
      <%= form.text_field :taxes_registry_number, class: "form-control" %>
    </div>

    <div>
      <%= form.label :country_code, "Pais", style: "display: block", class: "form-label mt-3" %>
      <%= form.select(:country_code, [["Chile", "CL"], ["Peru", "PE"], ["Ecuador", "EC"], ["Colombia", "CO"], ["Brazil", "BR"]], {}, { class: 'form-select' }) %>
    </div>

    <div>
      <%= form.label :company_address, "Dirección", style: "display: block", class: "form-label mt-3" %>
      <%= form.text_field :company_address, class: "form-control" %>
    </div>
    <div>
      <%= form.label :category, "Rubro", style: "display: block", class: "form-label mt-3" %>
      <%= form.select(:category_id, Category.all.pluck(:name, :id), {}, { class: 'form-select' }) %>
    </div>

    <div>
      <%= form.label :email_company, "Email", style: "display: block", class: "form-label mt-3" %>
      <%= form.text_field :email_company, class: "form-control" %>
    </div>

    <div class="mt-3">
      <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Agregar Responsable
      </a>
    </div>
    <div class="form-control mt-4 collapse" id="collapseExample">
      <div>
        <%= form.label :first_name, "Nombre(s) representante legal", style: "display: block", class: "form-label mt-3" %>
        <%= form.text_field :first_name, class: "form-control" %>
      </div>

      <div>
        <%= form.label :last_name, "Apellido(s) representante legal", style: "display: block", class: "form-label mt-3" %>
        <%= form.text_field :last_name, class: "form-control" %>
      </div>

      <div>
        <%= form.label :phone, "Telefono", style: "display: block", class: "form-label mt-3" %>
        <%= form.text_field :phone, class: "form-control" %>
      </div>

      <div>
        <%= form.label :identification_document_type, "Tipo de documento", style: "display: block", class: "form-label mt-3" %>
        <%= form.select(:identification_document_type, [["RUT", 1], ["RUC", 2], ["DNI", 3]], {}, { class: 'form-select' }) %>
      </div>

      <div>
        <%= form.label :identification_document_number, "Numero documento identidad", style: "display: block", class: "form-label mt-3" %>
        <%= form.text_field :identification_document_number, class: "form-control" %>
      </div>

      <div>
        <%= form.label :email, "Email", style: "display: block", class: "form-label mt-3" %>
        <%= form.text_field :email, class: "form-control" %>
      </div>

      <div>
        <%= form.label :person_address, "Dirección", style: "display: block", class: "form-label mt-3" %>
        <%= form.text_field :person_address, class: "form-control" %>
      </div>
    </div>

    <div>
        <% action = action_name == 'new' ? 'Crear' : 'Editar' %>
        <%= form.submit "#{action} compañia", class: "btn btn-primary mt-3" %>
    </div>
  <% end %>
</div>

app/views/party_company_details/_party_company_detail.html.erb
<tr id="<%= party_company_detail.id %>">
  <th scope="row"><%= party_company_detail.name %></th>
  <th scope="row"><%= t("models.#{party_company_detail.type}") %></th>
  <th scope="row"><%= party_company_detail.email %></th>
  <th scope="row"><%= party_company_detail.management %></th>
  <th scope="row">Administrador General</th>
  <th scope="row"><%= party_company_detail.updated_at %></th>  
</tr>

app/views/party_company_details/edit.html.erb
<h1>Editing party company detail</h1>

<%= render "form", party_company_detail: @party_company_detail %>

<br>

<div>
  <%= link_to "Show this party company detail", @party_company_detail %> |
  <%= link_to "Back to party company details", party_company_details_path %>
</div>

app/views/party_company_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Directorio</h1>

<div id="party_company_details">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Tipo</th>
        <th scope="col">Email</th>
        <th scope="col">Relacion</th>
        <th scope="col">Creado por</th>
        <th scope="col">Ultima actualizacion</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "party_company_detail", collection: @companies %>
    </tbody>
  </table>
</div>

app/views/party_company_details/new.html.erb
<div class="container">
  <%= render "form", party_company_detail: @party_company_detail %>
</div>
<br>

app/views/party_company_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @party_company_detail %>

<div>
  <%= link_to "Edit this party company detail", edit_party_company_detail_path(@party_company_detail) %> |
  <%= link_to "Back to party company details", party_company_details_path %>

  <%= button_to "Destroy this party company detail", @party_company_detail, method: :delete %>
</div>